### ISSUE TITLE
Region migration from FireBase to the Blockchain

### ISSUE THREAD

**Issue by Chrimle** [DavidZamanian/Bachelor-thesis-blockchain-for-medical-records#62]
The frontend needs to be adjusted slightly when fetching regions (and permissioned regions needs to actually be implemented).

What the blockchain/smart contract expects as parameters needs to be established; 

- is it the region name, which the smart contract itself looks up the regionID for?

- Or will the frontend not only receive the region name, but also the regionID?

> The safest approach, to me, is to have the frontend send the regionID, rather than the regionName.
> This however, requires a method for fetching regions (ID and name) to the frontend. 
(The ID for sending to the blockchain, and the name for displaying)
/ @Chrimle 

Any objections for the frontend to fetch both regionID and regionName from the blockchain? @hjernkrook

**Comment by hjernkrook** [comment]
If I understand you correctly, this is already being addressed by the branch `regionsInSmartContract`, where I have added support for fetching regions (both id and name) easily from the smart contract. The database will not at all be needed, I don't think. In all cases where a single parameter is given for the region, it is the id that should be given. There is no way of getting a region based on name, currently. If approved, this will be merged into master by tomorrow most likely, and then chain calls will be added to fetch regions, among other things.

**Comment by Chrimle** [comment]
Awesome, that's the confirmation I needed!

So, the frontend can get both name and ID from the smart contract. And, if permissions are changed, the frontend only send the list of regionIDs back to the smart contract. Awesome!
