### ISSUE TITLE
BankID should be removed from login-screen.

### ISSUE THREAD

**Issue by hjernkrook** [DavidZamanian/Bachelor-thesis-blockchain-for-medical-records#65]
Since we no longer mock it.

**Comment by Chrimle** [comment]
Very true. Just to keep the "magic-3": Should we replace the text with "Authenticate once - the rest is done automatically"? or something similar? Maybe mention permissions, and how, we check if someone has the permission to a certain action - without the need to "authenticate" once more?

What are some good alternatives?
