### ISSUE TITLE
Can we remove accounts as field in smart contract

### ISSUE THREAD

**Issue by hjernkrook** [DavidZamanian/Bachelor-thesis-blockchain-for-medical-records#73]
Accounts should maybe not be used as fields in the contract for privacy reasons, but I am unsure. I understand it as the account ideally working as a psedonym to hide behind, but this won't work if we connect the account and id really.

**Comment by Chrimle** [comment]
Has this been addressed? If not, could you clarify/elaborate on this. (Perhaps point to what place in the code this affects).

**Comment by hjernkrook** [comment]
@Chrimle it is addresses in the way that we cannot address it. The account addresses are needed as the smart contract is currently implemented. It is probably sub-optimal, but it will have to do.
