### ISSUE TITLE
Permitted Regions needs to be updated without re-logging in

### ISSUE THREAD

**Issue by hjernkrook** [DavidZamanian/Bachelor-thesis-blockchain-for-medical-records#76]
currently, permitted regions are only fetched upon logging in. This means that a change to the permissions settings will not be reflected within the same session. Now, a user must sign out and again log in to see the effects of the update. This needs to be addressed. Either by fetching the permitted regions each time the 'configure' button is pressed, or by fetching it anew upon an update. I think that the latter is the best approach.

**Comment by Chrimle** [comment]
I could fix this

**Comment by Chrimle** [comment]
This was due to the bug related to regionSnapshot and has been resolved.
