### ISSUE TITLE
Non-existing EHRs - Can we handle them?

### ISSUE THREAD

**Issue by hjernkrook** [DavidZamanian/Bachelor-thesis-blockchain-for-medical-records#78]
I haven't looked into the code for this yet, but this will need to be addressed shortly. 
When a patient has no previous EHR in the system, there will be no CID for that patient on the chain, nor anything to retrieve from IPFS and thus nothing to display.
We need to make sure that the system handles all these events correctly.

**Comment by Chrimle** [comment]
True, what happens `getEHR` doesn't have a CID? This sounds like it can be solved by a simple `if` the Smart Contract function does return a CID, download from that. Otherwise, ignore the downloading of the files. HOWEVER, this may as well bring up another issue: #85 .
