### ISSUE TITLE
Stall EHR-upload until MetaMask signature

### ISSUE THREAD

**Issue by Chrimle** [DavidZamanian/Bachelor-thesis-blockchain-for-medical-records#87]
Currently, EHRs will be uploaded before MetaMask requests a signature

**Comment by hjernkrook** [comment]
Huh, interesting. Is this addressed by #92 or will this require further attention?

**Comment by Chrimle** [comment]
This was stalled, because it required "UpdateCID" found in #83.

**Comment by Chrimle** [comment]
This appears to be a non-issue, because we cannot stall the upload because the upload returns the CID to begin with...
